CREATE TABLE [dbo].[SUCURSAL]
(
[IDSUC] [int] NOT NULL IDENTITY(1, 1),
[NOMSUC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DIRSUC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IDJEFSUC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUCURSAL] ADD CONSTRAINT [SUCURSAL_pk] PRIMARY KEY CLUSTERED ([IDSUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUCURSAL] ADD CONSTRAINT [SUCURSAL_JEFE_SUCURSAL] FOREIGN KEY ([IDJEFSUC]) REFERENCES [dbo].[JEFE_SUCURSAL] ([IDJEFSUC])
GO
