CREATE TABLE [dbo].[CLIENTE]
(
[IDCLI] [int] NOT NULL IDENTITY(1, 1),
[NOMCLI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APECLI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNICLI] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CELCLI] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DIRCLI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_pk] PRIMARY KEY CLUSTERED ([IDCLI]) ON [PRIMARY]
GO
