CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PREPRO] [decimal] (10, 2) NOT NULL,
[STOPRO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED ([IDPRO]) ON [PRIMARY]
GO
