CREATE TABLE [dbo].[DESPACHADOR]
(
[IDDESP] [int] NOT NULL IDENTITY(1, 1),
[NOMDESP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APEDESP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNIDESP] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CELDESP] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DIRDESP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IDJEFSUC] [int] NOT NULL,
[IDSUC] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DESPACHADOR] ADD CONSTRAINT [DESPACHADOR_pk] PRIMARY KEY CLUSTERED ([IDDESP]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DESPACHADOR] ADD CONSTRAINT [DESPACHADOR_JEFE_SUCURSAL] FOREIGN KEY ([IDJEFSUC]) REFERENCES [dbo].[JEFE_SUCURSAL] ([IDJEFSUC])
GO
ALTER TABLE [dbo].[DESPACHADOR] ADD CONSTRAINT [DESPACHADOR_SUCURSAL] FOREIGN KEY ([IDSUC]) REFERENCES [dbo].[SUCURSAL] ([IDSUC])
GO
